using System.Runtime.CompilerServices;
using System.Text.Json.Nodes;

namespace Remex.Core.Tests.Routines;

/// <summary>
/// The shared routine fixtures (RemEx-pp0rt.3). Generated by <c>scripts/generate-routine-fixtures.py</c>
/// into this project's <c>Fixtures/Routines</c> and, byte for byte, into the Android unit-test
/// resources, so the C# and Kotlin mirrors are held to the same documents.
/// </summary>
internal static class RoutineFixtures
{
    public static string Dir => Path.Combine(AppContext.BaseDirectory, "Fixtures", "Routines");

    public static string ReadText(string file) => File.ReadAllText(Path.Combine(Dir, file));

    public static JsonNode ReadNode(string file) => JsonNode.Parse(ReadText(file))!;

    public static JsonObject Manifest => (JsonObject)ReadNode("manifest.json");

    public static IEnumerable<(string File, string Expected)> Validation =>
        Manifest["validation"]!.AsArray()
            .Select(n => (n!["file"]!.GetValue<string>(), n["expected"]!.GetValue<string>()));

    public static IEnumerable<(string File, string Type, string Slot)> Wire =>
        Manifest["wire"]!.AsArray()
            .Select(n => (n!["file"]!.GetValue<string>(), n["type"]!.GetValue<string>(), n["slot"]!.GetValue<string>()));

    public static IEnumerable<(string File, string Type, string Slot)> Rejected =>
        Manifest["rejected"]!.AsArray()
            .Select(n => (n!["file"]!.GetValue<string>(), n["type"]!.GetValue<string>(), n["slot"]!.GetValue<string>()));

    public static string RoutineRunsFile => Manifest["routineRuns"]!.GetValue<string>();

    public static string RepoRoot([CallerFilePath] string thisFile = "")
        => Path.GetFullPath(Path.Combine(Path.GetDirectoryName(thisFile)!, "..", ".."));

    /// <summary>The fixture source directory in the repo (not the build output copy).</summary>
    public static string SourceDir => Path.Combine(RepoRoot(), "remex.core.tests", "Fixtures", "Routines");

    /// <summary>The Android unit-test copy the Kotlin mirror reads.</summary>
    public static string AndroidDir =>
        Path.Combine(RepoRoot(), "remex.android", "app", "src", "test", "resources", "routines");
}
