package com.clindsay94.remex.routines.model

import java.math.BigDecimal
import org.json.JSONArray
import org.json.JSONObject

/**
 * The shared routine fixtures (RemEx-pp0rt.3), read from `src/test/resources/routines`. That
 * directory is a byte-for-byte copy of `remex.core.tests/Fixtures/Routines` (generated by
 * `scripts/generate-routine-fixtures.py`; the C# RoutineFixtureParityTests fails if they drift), so
 * the Kotlin and C# mirrors are held to the same documents.
 */
internal object RoutineFixtures {
    fun text(file: String): String {
        val resource = RoutineFixtures::class.java.classLoader!!.getResource("routines/$file")
            ?: error("fixture routines/$file is missing from the test resources")
        return resource.readText(Charsets.UTF_8)
    }

    fun json(file: String): JSONObject = JSONObject(text(file))

    private val manifest: JSONObject by lazy { json("manifest.json") }

    /** (file, expected first-failure code) for every validation fixture. */
    val validation: List<Pair<String, String>> by lazy {
        val array = manifest.getJSONArray("validation")
        (0 until array.length()).map { array.getJSONObject(it).let { o -> o.getString("file") to o.getString("expected") } }
    }

    data class Wire(val file: String, val type: String, val slot: String)

    val wire: List<Wire> by lazy {
        val array = manifest.getJSONArray("wire")
        (0 until array.length()).map {
            val o = array.getJSONObject(it)
            Wire(o.getString("file"), o.getString("type"), o.getString("slot"))
        }
    }

    /** Payloads both readers must refuse (a null list element). */
    val rejected: List<Wire> by lazy {
        val array = manifest.getJSONArray("rejected")
        (0 until array.length()).map {
            val o = array.getJSONObject(it)
            Wire(o.getString("file"), o.getString("type"), o.getString("slot"))
        }
    }

    val routineRunsFile: String by lazy { manifest.getString("routineRuns") }

    /**
     * JSON tree equality with numbers compared by value (`90` equals `90.0`), because org.json and
     * System.Text.Json spell some numbers differently while meaning the same one.
     */
    fun treeEquals(a: Any?, b: Any?): Boolean {
        val x = if (a == null) JSONObject.NULL else a
        val y = if (b == null) JSONObject.NULL else b
        return when {
            x is JSONObject && y is JSONObject -> {
                // keys(), not keySet(): the compile classpath is android.jar's org.json.
                val keys = x.keys().asSequence().toSet()
                keys == y.keys().asSequence().toSet() && keys.all { treeEquals(x.opt(it), y.opt(it)) }
            }
            x is JSONArray && y is JSONArray ->
                x.length() == y.length() && (0 until x.length()).all { treeEquals(x.opt(it), y.opt(it)) }
            x is Number && y is Number -> BigDecimal(x.toString()).compareTo(BigDecimal(y.toString())) == 0
            else -> x == y
        }
    }
}
