using System.Text.Json;
using Remex.Core.Theming.Mcu;

namespace Remex.Core.Tests.Theming;

/// <summary>
/// RemEx-4kv0g.8 (fix round 2): <see cref="MathUtils.Log1p"/> and <see cref="MathUtils.Expm1"/> are
/// transcribed directly from OpenJDK's <c>jdk.internal.math.FdLibm.Log1p.compute</c> /
/// <c>FdLibm.Expm1.compute</c> (Temurin 21.0.x, <c>java.base/java/lang/FdLibm.java</c>) — the exact
/// algorithm <c>java.lang.Math</c>/<c>StrictMath</c> (and, by lineage, Android bionic libm/ART) use.
///
/// The round-1 fix ported musl libc's <c>log1p.c</c>/<c>expm1.c</c> instead. Those are FreeBSD msun's
/// REWRITE of the 1993 SunPro fdlibm source — same constants, a DIFFERENT algorithm (even/odd
/// polynomial split with a single left-to-right final sum, different short-circuit thresholds). The
/// round-1 re-review compiled that port and diffed it against JDK 21 <c>StrictMath.log1p</c> over
/// 736,019 inputs: 349 mismatches for Log1p (207 in the CAM16-UCS domain <c>0.0228*m</c>),
/// 0 for Expm1. This file's oracle is therefore the actual JDK FdLibm output — read from
/// <c>Fixtures/fdlibm-vectors.json</c>, generated by feeding the same inputs through
/// <c>StrictMath.log1p</c>/<c>StrictMath.expm1</c> — and every comparison below is bit-exact
/// (<see cref="BitConverter.DoubleToInt64Bits(double)"/> equality), not a ULP-tolerance band: a
/// faithful line-for-line transcription of the same algorithm has no excuse for even 1 ulp of drift.
///
/// Full 736,019-input comparison against JDK 21 (<c>compare2.py</c> / <c>csoracle</c>), after this
/// fix: 0 mismatches for Log1p, 0 mismatches for Expm1 (see task-3-report.md, fix round 2).
/// </summary>
public class MathUtilsLog1pExpm1Tests
{
    private static JsonDocument LoadFixture()
        => JsonDocument.Parse(File.ReadAllBytes(Path.Combine(AppContext.BaseDirectory, "Fixtures", "fdlibm-vectors.json")));

    private static double FromHexBits(string hex) => BitConverter.Int64BitsToDouble(unchecked((long)Convert.ToUInt64(hex, 16)));

    private static void AssertBitExact(string xHex, string expectedHex, Func<double, double> fn, string fnName)
    {
        double x = FromHexBits(xHex);
        double expected = FromHexBits(expectedHex);
        double actual = fn(x);
        if (double.IsNaN(expected))
        {
            Assert.True(double.IsNaN(actual), $"{fnName}({x:R}) [{xHex}]: expected NaN, got {actual:R}");
            return;
        }
        Assert.True(
            BitConverter.DoubleToInt64Bits(expected) == BitConverter.DoubleToInt64Bits(actual),
            $"{fnName}({x:R}) [{xHex}]: expected {expected:R} [{expectedHex}], got {actual:R} [{BitConverter.DoubleToInt64Bits(actual):x16}]");
    }

    [Fact]
    public void Log1p_IsBitExactAgainstTheJdkFdLibmFixture()
    {
        using var doc = LoadFixture();
        var vectors = doc.RootElement.GetProperty("log1p").EnumerateArray().ToArray();
        Assert.True(vectors.Length > 20000, $"expected a dense fixture, got {vectors.Length} rows");
        foreach (var v in vectors)
        {
            var arr = v.EnumerateArray().ToArray();
            AssertBitExact(arr[0].GetString()!, arr[1].GetString()!, MathUtils.Log1p, "Log1p");
        }
    }

    [Fact]
    public void Expm1_IsBitExactAgainstTheJdkFdLibmFixture()
    {
        using var doc = LoadFixture();
        var vectors = doc.RootElement.GetProperty("expm1").EnumerateArray().ToArray();
        Assert.True(vectors.Length > 20000, $"expected a dense fixture, got {vectors.Length} rows");
        foreach (var v in vectors)
        {
            var arr = v.EnumerateArray().ToArray();
            AssertBitExact(arr[0].GetString()!, arr[1].GetString()!, MathUtils.Expm1, "Expm1");
        }
    }

    [Fact]
    public void Log1p_SpecialValues()
    {
        Assert.Equal(0.0, MathUtils.Log1p(0.0));
        // fdlibm's Log1p.compute has no explicit -0.0 short path; -0.0 falls through the |x| < 2**-29
        // branch and returns x unchanged (verified bit-exact against StrictMath.log1p(-0.0) below).
        Assert.Equal(BitConverter.DoubleToInt64Bits(-0.0), BitConverter.DoubleToInt64Bits(MathUtils.Log1p(-0.0)));
        Assert.Equal(double.NegativeInfinity, MathUtils.Log1p(-1.0));
        Assert.True(double.IsNaN(MathUtils.Log1p(-2.0)));
        Assert.True(double.IsNaN(MathUtils.Log1p(double.NegativeInfinity)));
        Assert.True(double.IsNaN(MathUtils.Log1p(double.NaN)));
        Assert.Equal(double.PositiveInfinity, MathUtils.Log1p(double.PositiveInfinity));
    }

    [Fact]
    public void Expm1_SpecialValues()
    {
        Assert.Equal(0.0, MathUtils.Expm1(0.0));
        Assert.True(double.IsNaN(MathUtils.Expm1(double.NaN)));
        Assert.Equal(double.PositiveInfinity, MathUtils.Expm1(double.PositiveInfinity));
        Assert.Equal(-1.0, MathUtils.Expm1(double.NegativeInfinity));
    }

    [Fact]
    public void Expm1_OverflowsPastOThreshold()
    {
        Assert.True(double.IsPositiveInfinity(MathUtils.Expm1(710.0)));
        Assert.True(double.IsPositiveInfinity(MathUtils.Expm1(800.0)));
    }

    [Theory]
    // MathUtils.ToRadians/ToDegrees (review fix #2): java.lang.Math's constant-multiply, not (x*PI)/180.
    [InlineData(0.0, 0.0)] [InlineData(90.0, 1.5707963267948966)] [InlineData(180.0, 3.141592653589793)]
    [InlineData(360.0, 6.283185307179586)] [InlineData(-45.0, -0.7853981633974483)]
    public void ToRadians_UsesJavaConstant(double degrees, double expectedRadians) => Assert.Equal(expectedRadians, MathUtils.ToRadians(degrees));

    [Theory]
    [InlineData(0.0, 0.0)] [InlineData(1.5707963267948966, 90.0)] [InlineData(3.141592653589793, 180.0)]
    [InlineData(6.283185307179586, 360.0)] [InlineData(-0.7853981633974483, -45.0)]
    public void ToDegrees_UsesJavaConstant(double radians, double expectedDegrees) => Assert.Equal(expectedDegrees, MathUtils.ToDegrees(radians));
}
