//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remex.Desktop.Localization {
    using System;
    using System.Reflection;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Remex.Desktop.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Validation
        public static string Connection_PcAddressRequired => ResourceManager.GetString("Connection_PcAddressRequired", resourceCulture)!;

        // Navigation
        public static string Nav_Home => ResourceManager.GetString("Nav_Home", resourceCulture)!;
        public static string Nav_Sensors => ResourceManager.GetString("Nav_Sensors", resourceCulture)!;
        public static string Nav_Launcher => ResourceManager.GetString("Nav_Launcher", resourceCulture)!;
        public static string Nav_Settings => ResourceManager.GetString("Nav_Settings", resourceCulture)!;

        // Common Buttons
        public static string Btn_Connect => ResourceManager.GetString("Btn_Connect", resourceCulture)!;
        public static string Btn_Disconnect => ResourceManager.GetString("Btn_Disconnect", resourceCulture)!;
        public static string Btn_Cancel => ResourceManager.GetString("Btn_Cancel", resourceCulture)!;
        public static string Btn_Save => ResourceManager.GetString("Btn_Save", resourceCulture)!;
        public static string Btn_Apply => ResourceManager.GetString("Btn_Apply", resourceCulture)!;
        public static string Btn_Browse => ResourceManager.GetString("Btn_Browse", resourceCulture)!;
        public static string Btn_Discover => ResourceManager.GetString("Btn_Discover", resourceCulture)!;
        public static string Btn_Start => ResourceManager.GetString("Btn_Start", resourceCulture)!;
        public static string Btn_Stop => ResourceManager.GetString("Btn_Stop", resourceCulture)!;

        // Remote View
        public static string Remote_Header => ResourceManager.GetString("Remote_Header", resourceCulture)!;
        public static string Remote_Subheader => ResourceManager.GetString("Remote_Subheader", resourceCulture)!;
        public static string Remote_Graceful => ResourceManager.GetString("Remote_Graceful", resourceCulture)!;
        public static string Remote_Forced => ResourceManager.GetString("Remote_Forced", resourceCulture)!;
        public static string Remote_Lock => ResourceManager.GetString("Remote_Lock", resourceCulture)!;
        public static string Remote_SignOut => ResourceManager.GetString("Remote_SignOut", resourceCulture)!;
        public static string Remote_Shutdown => ResourceManager.GetString("Remote_Shutdown", resourceCulture)!;
        public static string Remote_Restart => ResourceManager.GetString("Remote_Restart", resourceCulture)!;
        public static string Remote_Sleep => ResourceManager.GetString("Remote_Sleep", resourceCulture)!;
        public static string Remote_Hibernate => ResourceManager.GetString("Remote_Hibernate", resourceCulture)!;
        public static string Remote_ForceShutdown => ResourceManager.GetString("Remote_ForceShutdown", resourceCulture)!;
        public static string Remote_ForceRestart => ResourceManager.GetString("Remote_ForceRestart", resourceCulture)!;
        public static string Remote_RebootUefi => ResourceManager.GetString("Remote_RebootUefi", resourceCulture)!;

        // Settings
        public static string Settings_Header => ResourceManager.GetString("Settings_Header", resourceCulture)!;
        public static string Settings_Back => ResourceManager.GetString("Settings_Back", resourceCulture)!;
        public static string Settings_SaveChanges => ResourceManager.GetString("Settings_SaveChanges", resourceCulture)!;
        public static string Settings_SavedStatus => ResourceManager.GetString("Settings_SavedStatus", resourceCulture)!;
        public static string Settings_Connection => ResourceManager.GetString("Settings_Connection", resourceCulture)!;
        public static string Settings_HostAddress => ResourceManager.GetString("Settings_HostAddress", resourceCulture)!;
        public static string Settings_SaveReconnect => ResourceManager.GetString("Settings_SaveReconnect", resourceCulture)!;
        public static string Settings_Layout => ResourceManager.GetString("Settings_Layout", resourceCulture)!;
        public static string Settings_SnapToGrid => ResourceManager.GetString("Settings_SnapToGrid", resourceCulture)!;
        public static string Settings_SnapToGridDesc => ResourceManager.GetString("Settings_SnapToGridDesc", resourceCulture)!;
        public static string Settings_GridSize => ResourceManager.GetString("Settings_GridSize", resourceCulture)!;
        public static string Settings_PinnedSensors => ResourceManager.GetString("Settings_PinnedSensors", resourceCulture)!;
        public static string Settings_PinnedSensorsDesc => ResourceManager.GetString("Settings_PinnedSensorsDesc", resourceCulture)!;
        public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture)!;

        // Home
        public static string Home_NoPinnedSensorsHint => ResourceManager.GetString("Home_NoPinnedSensorsHint", resourceCulture)!;

        // Task Manager
        public static string TaskMgr_Header => ResourceManager.GetString("TaskMgr_Header", resourceCulture)!;
        public static string TaskMgr_Subheader => ResourceManager.GetString("TaskMgr_Subheader", resourceCulture)!;
        public static string TaskMgr_SearchPlaceholder => ResourceManager.GetString("TaskMgr_SearchPlaceholder", resourceCulture)!;
        public static string TaskMgr_KillProcess => ResourceManager.GetString("TaskMgr_KillProcess", resourceCulture)!;
        public static string TaskMgr_SortName => ResourceManager.GetString("TaskMgr_SortName", resourceCulture)!;
        public static string TaskMgr_SortCpu => ResourceManager.GetString("TaskMgr_SortCpu", resourceCulture)!;
        public static string TaskMgr_SortRam => ResourceManager.GetString("TaskMgr_SortRam", resourceCulture)!;

        // App Launcher
        public static string AppLauncher_Header => ResourceManager.GetString("AppLauncher_Header", resourceCulture)!;
        public static string AppLauncher_Subheader => ResourceManager.GetString("AppLauncher_Subheader", resourceCulture)!;
        public static string AppLauncher_AddProgram => ResourceManager.GetString("AppLauncher_AddProgram", resourceCulture)!;
        public static string AppLauncher_NoApps => ResourceManager.GetString("AppLauncher_NoApps", resourceCulture)!;
        public static string AppLauncher_MoveLeft => ResourceManager.GetString("AppLauncher_MoveLeft", resourceCulture)!;
        public static string AppLauncher_MoveRight => ResourceManager.GetString("AppLauncher_MoveRight", resourceCulture)!;
        public static string AppLauncher_Remove => ResourceManager.GetString("AppLauncher_Remove", resourceCulture)!;

        // Add Program
        public static string AddProgram_Title => ResourceManager.GetString("AddProgram_Title", resourceCulture)!;
        public static string AddProgram_Header => ResourceManager.GetString("AddProgram_Header", resourceCulture)!;
        public static string AddProgram_ExePath => ResourceManager.GetString("AddProgram_ExePath", resourceCulture)!;
        public static string AddProgram_DisplayName => ResourceManager.GetString("AddProgram_DisplayName", resourceCulture)!;
        public static string AddProgram_AccentColor => ResourceManager.GetString("AddProgram_AccentColor", resourceCulture)!;
        public static string AddProgram_IconPreview => ResourceManager.GetString("AddProgram_IconPreview", resourceCulture)!;

        // Tray Flyout
        public static string TrayFlyout_Home => ResourceManager.GetString("TrayFlyout_Home", resourceCulture)!;
        public static string TrayFlyout_Workspace => ResourceManager.GetString("TrayFlyout_Workspace", resourceCulture)!;

        // Canvas / Dashboard
        public static string Canvas_Header => ResourceManager.GetString("Canvas_Header", resourceCulture)!;
        public static string Canvas_Connection => ResourceManager.GetString("Canvas_Connection", resourceCulture)!;
        public static string Canvas_Actions => ResourceManager.GetString("Canvas_Actions", resourceCulture)!;
        public static string Canvas_Latency => ResourceManager.GetString("Canvas_Latency", resourceCulture)!;
        public static string Canvas_Avg => ResourceManager.GetString("Canvas_Avg", resourceCulture)!;
        public static string Canvas_Max => ResourceManager.GetString("Canvas_Max", resourceCulture)!;
        public static string Canvas_ActiveSensors => ResourceManager.GetString("Canvas_ActiveSensors", resourceCulture)!;
        public static string Canvas_NewSensors => ResourceManager.GetString("Canvas_NewSensors", resourceCulture)!;
        public static string Canvas_AddCard => ResourceManager.GetString("Canvas_AddCard", resourceCulture)!;
        public static string Canvas_Save => ResourceManager.GetString("Canvas_Save", resourceCulture)!;
        public static string Canvas_Sync => ResourceManager.GetString("Canvas_Sync", resourceCulture)!;
        public static string Canvas_Sensors => ResourceManager.GetString("Canvas_Sensors", resourceCulture)!;
        public static string Canvas_Ping => ResourceManager.GetString("Canvas_Ping", resourceCulture)!;
        public static string Canvas_CancelConnect => ResourceManager.GetString("Canvas_CancelConnect", resourceCulture)!;
        public static string Canvas_Disconnect => ResourceManager.GetString("Canvas_Disconnect", resourceCulture)!;

        // Remote Desktop
        public static string RemoteDesktop_Header => ResourceManager.GetString("RemoteDesktop_Header", resourceCulture)!;
        public static string RemoteDesktop_Quality => ResourceManager.GetString("RemoteDesktop_Quality", resourceCulture)!;
        public static string RemoteDesktop_Scale => ResourceManager.GetString("RemoteDesktop_Scale", resourceCulture)!;
        public static string RemoteDesktop_Fps => ResourceManager.GetString("RemoteDesktop_Fps", resourceCulture)!;
        public static string RemoteDesktop_StreamError => ResourceManager.GetString("RemoteDesktop_StreamError", resourceCulture)!;
        public static string RemoteDesktop_PlaceholderTitle => ResourceManager.GetString("RemoteDesktop_PlaceholderTitle", resourceCulture)!;
        public static string RemoteDesktop_PlaceholderHint => ResourceManager.GetString("RemoteDesktop_PlaceholderHint", resourceCulture)!;
        public static string RemoteDesktop_ToggleCursorPad => ResourceManager.GetString("RemoteDesktop_ToggleCursorPad", resourceCulture)!;
        public static string RemoteDesktop_ToggleFullscreen => ResourceManager.GetString("RemoteDesktop_ToggleFullscreen", resourceCulture)!;
        public static string RemoteDesktop_Fullscreen => ResourceManager.GetString("RemoteDesktop_Fullscreen", resourceCulture)!;
        public static string RemoteDesktop_ResolutionFormat => ResourceManager.GetString("RemoteDesktop_ResolutionFormat", resourceCulture)!;
        public static string RemoteDesktop_FpsFormat => ResourceManager.GetString("RemoteDesktop_FpsFormat", resourceCulture)!;
        public static string RemoteDesktop_QualityFormat => ResourceManager.GetString("RemoteDesktop_QualityFormat", resourceCulture)!;

        // Customization
        public static string Custom_BasePresets => ResourceManager.GetString("Custom_BasePresets", resourceCulture)!;
        public static string Custom_AdvancedTuning => ResourceManager.GetString("Custom_AdvancedTuning", resourceCulture)!;
        public static string Custom_CornerRadius => ResourceManager.GetString("Custom_CornerRadius", resourceCulture)!;
        public static string Custom_GlassOpacity => ResourceManager.GetString("Custom_GlassOpacity", resourceCulture)!;
        public static string Custom_GlowStrength => ResourceManager.GetString("Custom_GlowStrength", resourceCulture)!;
        public static string Custom_AccentColor => ResourceManager.GetString("Custom_AccentColor", resourceCulture)!;
        public static string Custom_BackgroundMode => ResourceManager.GetString("Custom_BackgroundMode", resourceCulture)!;
        public static string Custom_Atmosphere => ResourceManager.GetString("Custom_Atmosphere", resourceCulture)!;
        public static string Custom_Reset => ResourceManager.GetString("Custom_Reset", resourceCulture)!;

        // Status Messages
        public static string Status_Disconnected => ResourceManager.GetString("Status_Disconnected", resourceCulture)!;
        public static string Status_Connected => ResourceManager.GetString("Status_Connected", resourceCulture)!;
        public static string Status_Connecting => ResourceManager.GetString("Status_Connecting", resourceCulture)!;
        public static string Status_PingSent => ResourceManager.GetString("Status_PingSent", resourceCulture)!;
        public static string Status_ServerClosed => ResourceManager.GetString("Status_ServerClosed", resourceCulture)!;
        public static string Status_NoHostsFound => ResourceManager.GetString("Status_NoHostsFound", resourceCulture)!;
        public static string Status_SearchingHosts => ResourceManager.GetString("Status_SearchingHosts", resourceCulture)!;
        public static string Status_DiscoveryUnavailable => ResourceManager.GetString("Status_DiscoveryUnavailable", resourceCulture)!;
        public static string Status_PongNoTimestamp => ResourceManager.GetString("Status_PongNoTimestamp", resourceCulture)!;
        public static string Status_Pong => ResourceManager.GetString("Status_Pong", resourceCulture)!;
        public static string Status_NotStreaming => ResourceManager.GetString("Status_NotStreaming", resourceCulture)!;
        public static string Status_Streaming => ResourceManager.GetString("Status_Streaming", resourceCulture)!;
        public static string Status_SelfConnection => ResourceManager.GetString("Status_SelfConnection", resourceCulture)!;
        public static string Status_ConnectionSaved => ResourceManager.GetString("Status_ConnectionSaved", resourceCulture)!;
        public static string Status_ZoomFormat => ResourceManager.GetString("Status_ZoomFormat", resourceCulture)!;
        public static string Status_PadCompact => ResourceManager.GetString("Status_PadCompact", resourceCulture)!;
        public static string Status_PadFull => ResourceManager.GetString("Status_PadFull", resourceCulture)!;
        public static string Status_PadCompactTooltip => ResourceManager.GetString("Status_PadCompactTooltip", resourceCulture)!;
        public static string Status_PadFullTooltip => ResourceManager.GetString("Status_PadFullTooltip", resourceCulture)!;

        // Service Status
        public static string Service_HostUnavailable => ResourceManager.GetString("Service_HostUnavailable", resourceCulture)!;
        public static string Service_HostUnavailableHint => ResourceManager.GetString("Service_HostUnavailableHint", resourceCulture)!;
        public static string Status_ConnectionCancelled => ResourceManager.GetString("Status_ConnectionCancelled", resourceCulture)!;
        public static string Status_ConnectionTimedOut => ResourceManager.GetString("Status_ConnectionTimedOut", resourceCulture)!;

        // WoL Status
        public static string Wol_EnterMac => ResourceManager.GetString("Wol_EnterMac", resourceCulture)!;
        public static string Wol_SendingViaHost => ResourceManager.GetString("Wol_SendingViaHost", resourceCulture)!;
        public static string Wol_SendingLocal => ResourceManager.GetString("Wol_SendingLocal", resourceCulture)!;
        public static string Wol_SentToFormat => ResourceManager.GetString("Wol_SentToFormat", resourceCulture)!;
        public static string Wol_SuccessFormat => ResourceManager.GetString("Wol_SuccessFormat", resourceCulture)!;
        public static string Wol_ErrorFormat => ResourceManager.GetString("Wol_ErrorFormat", resourceCulture)!;
        public static string Wol_LockSent => ResourceManager.GetString("Wol_LockSent", resourceCulture)!;
        public static string Wol_ShutdownSent => ResourceManager.GetString("Wol_ShutdownSent", resourceCulture)!;
        public static string Wol_ForceShutdownSent => ResourceManager.GetString("Wol_ForceShutdownSent", resourceCulture)!;
        public static string Wol_RestartSent => ResourceManager.GetString("Wol_RestartSent", resourceCulture)!;
        public static string Wol_ForceRestartSent => ResourceManager.GetString("Wol_ForceRestartSent", resourceCulture)!;
        public static string Wol_RebootUefiSent => ResourceManager.GetString("Wol_RebootUefiSent", resourceCulture)!;
        public static string Wol_SleepSent => ResourceManager.GetString("Wol_SleepSent", resourceCulture)!;
        public static string Wol_HibernateSent => ResourceManager.GetString("Wol_HibernateSent", resourceCulture)!;
        public static string Wol_SignOutSent => ResourceManager.GetString("Wol_SignOutSent", resourceCulture)!;

        // Phase 4: Live Localization keys
        public static string Canvas_GraphType => ResourceManager.GetString("Canvas_GraphType", resourceCulture)!;
        public static string Canvas_LockPC => ResourceManager.GetString("Canvas_LockPC", resourceCulture)!;
        public static string Canvas_RebootUefi => ResourceManager.GetString("Canvas_RebootUefi", resourceCulture)!;
        public static string Canvas_TogglePinToHome => ResourceManager.GetString("Canvas_TogglePinToHome", resourceCulture)!;
        public static string RemoteDesktop_ExitFullscreenTip => ResourceManager.GetString("RemoteDesktop_ExitFullscreenTip", resourceCulture)!;
        public static string RemoteDesktop_Host => ResourceManager.GetString("RemoteDesktop_Host", resourceCulture)!;
        public static string RemoteDesktop_HostWatermark => ResourceManager.GetString("RemoteDesktop_HostWatermark", resourceCulture)!;
        public static string RemoteDesktop_Pad => ResourceManager.GetString("RemoteDesktop_Pad", resourceCulture)!;
        public static string RemoteDesktop_PenModeHint => ResourceManager.GetString("RemoteDesktop_PenModeHint", resourceCulture)!;
        public static string RemoteDesktop_ResetZoom => ResourceManager.GetString("RemoteDesktop_ResetZoom", resourceCulture)!;
        public static string RemoteDesktop_StylusHint => ResourceManager.GetString("RemoteDesktop_StylusHint", resourceCulture)!;
        public static string RemoteDesktop_StylusModeTip => ResourceManager.GetString("RemoteDesktop_StylusModeTip", resourceCulture)!;
        public static string RemoteDesktop_SwitchPadModeTip => ResourceManager.GetString("RemoteDesktop_SwitchPadModeTip", resourceCulture)!;
        public static string RemoteDesktop_ToggleCompactPadTip => ResourceManager.GetString("RemoteDesktop_ToggleCompactPadTip", resourceCulture)!;
        public static string RemoteDesktop_ToggleCursorPadTip => ResourceManager.GetString("RemoteDesktop_ToggleCursorPadTip", resourceCulture)!;
        public static string RemoteDesktop_ToggleFullscreenTip => ResourceManager.GetString("RemoteDesktop_ToggleFullscreenTip", resourceCulture)!;
        public static string RemoteDesktop_TogglePen => ResourceManager.GetString("RemoteDesktop_TogglePen", resourceCulture)!;
        public static string RemoteDesktop_ToggleStylusModeTip => ResourceManager.GetString("RemoteDesktop_ToggleStylusModeTip", resourceCulture)!;
        public static string RemoteDesktop_TouchHint => ResourceManager.GetString("RemoteDesktop_TouchHint", resourceCulture)!;
        public static string Settings_General => ResourceManager.GetString("Settings_General", resourceCulture)!;
        public static string Settings_Help => ResourceManager.GetString("Settings_Help", resourceCulture)!;
        public static string Settings_ReplayTutorial => ResourceManager.GetString("Settings_ReplayTutorial", resourceCulture)!;
        public static string Settings_ReplayTutorialTooltip => ResourceManager.GetString("Settings_ReplayTutorialTooltip", resourceCulture)!;
        public static string Shell_OpenSettings => ResourceManager.GetString("Shell_OpenSettings", resourceCulture)!;
        public static string TaskMgr_CpuLabel => ResourceManager.GetString("TaskMgr_CpuLabel", resourceCulture)!;
        public static string TaskMgr_MemLabel => ResourceManager.GetString("TaskMgr_MemLabel", resourceCulture)!;
        public static string Tutorial_P1_Diagram => ResourceManager.GetString("Tutorial_P1_Diagram", resourceCulture)!;
        public static string Tutorial_SkipTooltip => ResourceManager.GetString("Tutorial_SkipTooltip", resourceCulture)!;

        // Phase 4: misc-views keys
        public static string AddProgram_WatermarkColor => ResourceManager.GetString("AddProgram_WatermarkColor", resourceCulture)!;
        public static string AddProgram_WatermarkName => ResourceManager.GetString("AddProgram_WatermarkName", resourceCulture)!;
        public static string AddProgram_WatermarkPath => ResourceManager.GetString("AddProgram_WatermarkPath", resourceCulture)!;
        public static string Dashboard_Connect => ResourceManager.GetString("Dashboard_Connect", resourceCulture)!;
        public static string TrayFlyout_Title => ResourceManager.GetString("TrayFlyout_Title", resourceCulture)!;
    }
}
